### PR TITLE
Add time to the title for events in month view calendar

### PR DESCRIPTION
**Pull request by ryzngard**
To resolve [Calendar: Display Time in Event Quick View](https://trello.com/c/EEwxBL0X/20-calendar-display-time-in-event-quick-view)

image

### CODE REVIEW

**Comment by ryzngard** [comment]
Q: Does the time need to be adjusted to local time, or is it already handled correctly before data makes it to the calendar?

**Comment by grishrl** [comment]
The times are automatically adjusted to the clients timezone; however if we can figure out a way to get a time zone displayed that would be good

**Comment by grishrl** [comment]
This is good; but I think the trailing second is going to cause some disjointing from what we're displaying in the other places; the UtilitiesService should have a method; getTimeFromMs() that will return you a formatted string of time that matches the other times; there is also a getSuffixFromMs

**Comment by grishrl** [comment]
this looks good. I am ready to merge it; I also would love if you can add this to the src/app/match-view
This component is the base component for displaying all of our matches at various places around the site

**Pull request merged**
